# 과제 1. Data Processing with Pandas

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
data = pd.read_csv("train_ver2.csv")
data.head()

C:\Users\33637\AppData\Local\Temp\ipykernel_9804\1058687236.py:1: DtypeWarning: Columns (0: age, 1: antiguedad, 2: indrel_1mes, 3: conyuemp) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("train_ver2.csv")

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,2015-01-28,1375586,N,ES,H,35,2015-01-12,0.0,6,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,2015-01-28,1050611,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,2015-01-28,1050612,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,2015-01-28,1050613,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,2015-01-28,1050614,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

Q1：**마지막 달(2016-05-28)**의 데이터에서 **nomprov(거주 도시/주)**를 기준으로 그룹화하세요.
- 고객 수, 평균 소득, 소득 중앙값, 평균 나이를 계산하세요.
- 고객 수가 50명 이상인 도시만 남기세요.
- 평균 소득을 기준으로 내림차순 정렬하여 상위 5개 도시를 출력하세요.

In [3]:
data_lastmonth = data.loc[data['fecha_dato'] == '2016-05-28']

data_lastmonth

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
12715856,2016-05-28,657640,N,ES,H,68,2006-11-17,0.0,114,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
12715857,2016-05-28,657788,N,ES,H,42,2006-11-18,0.0,114,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
12715858,2016-05-28,657795,N,ES,V,44,2006-11-18,0.0,114,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
12715859,2016-05-28,657790,N,ES,V,42,2006-11-18,0.0,114,1.0,...,0,0,0,0,1,0,0,1.0,1.0,1
12715860,2016-05-28,657794,N,ES,H,49,2006-11-18,0.0,114,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13647304,2016-05-28,1166765,N,ES,V,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647305,2016-05-28,1166764,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647306,2016-05-28,1166763,N,ES,H,47,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647307,2016-05-28,1166789,N,ES,H,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647308,2016-05-28,1550586,N,ES,H,37,2016-05-13,1.0,0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [4]:
province_summary = data_lastmonth.groupby('nomprov' , as_index=False).agg(
    Customer_count = ('ncodpers' , 'count'),
    Average_income = ('renta' , 'mean'),
    Median_income = ('renta' , 'median'),
    Average_age = ('age' , 'mean')
)

province_summary

,nomprov,Customer_count,Average_income,Median_income,Average_age
0,ALAVA,2597,132838.933333,103321.140,46.090104
1,ALBACETE,7792,82970.140154,78566.325,32.976771
2,ALICANTE,22210,87142.959076,67332.870,38.883116
3,ALMERIA,4317,84851.186250,72932.925,40.165393
4,ASTURIAS,18332,101311.341324,87085.140,38.950524
5,AVILA,2632,76155.498608,67509.345,36.402736
6,BADAJOZ,12949,72130.066952,62307.675,31.073442
7,"BALEARS, ILLES",9143,171890.951564,122837.220,39.74877
8,BARCELONA,88754,164584.843157,130877.160,39.865144
9,BIZKAIA,12528,110828.564000,97637.505,51.057391
10,BURGOS,6660,97780.229124,89299.890,38.092042
11,CACERES,8605,75454.406775,67716.000,31.451017
12,CADIZ,19829,98772.353515,79068.720,35.83156
13,CANTABRIA,10843,121170.217007,95250.510,41.30047
14,CASTELLON,7168,79028.432511,66454.080,35.766741
15,CEUTA,513,200515.885152,128699.580,44.007797
16,CIUDAD REAL,8096,70008.773617,62213.970,33.73876
17,CORDOBA,9857,85811.520086,69069.090,36.069697
18,"CORUÑA, A",28771,112581.079748,97389.315,33.799103
19,CUENCA,3793,69748.533755,66539.715,32.890852
20,GIPUZKOA,4887,127185.417857,87024.930,48.131164
21,GIRONA,6313,145193.823741,108908.340,36.125297
22,GRANADA,12426,96544.954543,82354.560,38.388379
23,GUADALAJARA,4695,95403.940147,92483.205,40.076464
24,HUELVA,8032,76732.887707,68897.520,33.397037
25,HUESCA,2795,89253.640457,73531.980,36.062612
26,JAEN,4509,76996.493517,67777.635,40.488357
27,LEON,5731,93490.714165,80953.410,42.878555
28,LERIDA,5439,81517.969975,64772.640,33.566281
29,LUGO,5670,76458.005733,64304.880,31.53545
30,MADRID,298841,178362.993637,138024.135,45.205564
31,MALAGA,24583,120920.857735,94961.910,38.502298
32,MELILLA,641,149071.944149,117718.365,45.329173
33,MURCIA,27795,78943.243629,67794.735,31.878683
34,NAVARRA,6023,114208.460625,83410.935,44.020588
35,OURENSE,5615,83135.325995,79009.830,31.565806
36,PALENCIA,3319,93114.083452,86602.185,35.424827
37,"PALMAS, LAS",16361,100171.383055,80591.610,37.62325
38,PONTEVEDRA,18990,113397.605584,97699.890,32.61227
39,"RIOJA, LA",5816,99366.831511,89486.910,41.501891
40,SALAMANCA,11093,105520.396300,89750.880,34.524745
41,SANTA CRUZ DE TENERIFE,5119,102131.308182,82331.550,44.650713
42,SEGOVIA,2881,98794.885055,89524.470,38.437348
43,SEVILLA,40581,117368.868903,92369.460,38.164806
44,SORIA,1261,87837.921027,78559.230,38.49088
45,TARRAGONA,7650,104479.600944,87640.425,37.742745
46,TERUEL,1538,88168.578000,76778.040,32.584525
47,TOLEDO,12690,80116.487937,68747.730,35.999921
48,VALENCIA,48103,89296.188278,72734.910,39.106854
49,VALLADOLID,16044,101641.794166,92628.285,38.150087
50,ZAMORA,3433,83752.301334,74767.500,33.491407
51,ZARAGOZA,23198,110172.519208,99607.890,41.006035

In [5]:
province_summary = province_summary.loc[province_summary['Customer_count'] >= 50]
province_summary

,nomprov,Customer_count,Average_income,Median_income,Average_age
0,ALAVA,2597,132838.933333,103321.140,46.090104
1,ALBACETE,7792,82970.140154,78566.325,32.976771
2,ALICANTE,22210,87142.959076,67332.870,38.883116
3,ALMERIA,4317,84851.186250,72932.925,40.165393
4,ASTURIAS,18332,101311.341324,87085.140,38.950524
5,AVILA,2632,76155.498608,67509.345,36.402736
6,BADAJOZ,12949,72130.066952,62307.675,31.073442
7,"BALEARS, ILLES",9143,171890.951564,122837.220,39.74877
8,BARCELONA,88754,164584.843157,130877.160,39.865144
9,BIZKAIA,12528,110828.564000,97637.505,51.057391
10,BURGOS,6660,97780.229124,89299.890,38.092042
11,CACERES,8605,75454.406775,67716.000,31.451017
12,CADIZ,19829,98772.353515,79068.720,35.83156
13,CANTABRIA,10843,121170.217007,95250.510,41.30047
14,CASTELLON,7168,79028.432511,66454.080,35.766741
15,CEUTA,513,200515.885152,128699.580,44.007797
16,CIUDAD REAL,8096,70008.773617,62213.970,33.73876
17,CORDOBA,9857,85811.520086,69069.090,36.069697
18,"CORUÑA, A",28771,112581.079748,97389.315,33.799103
19,CUENCA,3793,69748.533755,66539.715,32.890852
20,GIPUZKOA,4887,127185.417857,87024.930,48.131164
21,GIRONA,6313,145193.823741,108908.340,36.125297
22,GRANADA,12426,96544.954543,82354.560,38.388379
23,GUADALAJARA,4695,95403.940147,92483.205,40.076464
24,HUELVA,8032,76732.887707,68897.520,33.397037
25,HUESCA,2795,89253.640457,73531.980,36.062612
26,JAEN,4509,76996.493517,67777.635,40.488357
27,LEON,5731,93490.714165,80953.410,42.878555
28,LERIDA,5439,81517.969975,64772.640,33.566281
29,LUGO,5670,76458.005733,64304.880,31.53545
30,MADRID,298841,178362.993637,138024.135,45.205564
31,MALAGA,24583,120920.857735,94961.910,38.502298
32,MELILLA,641,149071.944149,117718.365,45.329173
33,MURCIA,27795,78943.243629,67794.735,31.878683
34,NAVARRA,6023,114208.460625,83410.935,44.020588
35,OURENSE,5615,83135.325995,79009.830,31.565806
36,PALENCIA,3319,93114.083452,86602.185,35.424827
37,"PALMAS, LAS",16361,100171.383055,80591.610,37.62325
38,PONTEVEDRA,18990,113397.605584,97699.890,32.61227
39,"RIOJA, LA",5816,99366.831511,89486.910,41.501891
40,SALAMANCA,11093,105520.396300,89750.880,34.524745
41,SANTA CRUZ DE TENERIFE,5119,102131.308182,82331.550,44.650713
42,SEGOVIA,2881,98794.885055,89524.470,38.437348
43,SEVILLA,40581,117368.868903,92369.460,38.164806
44,SORIA,1261,87837.921027,78559.230,38.49088
45,TARRAGONA,7650,104479.600944,87640.425,37.742745
46,TERUEL,1538,88168.578000,76778.040,32.584525
47,TOLEDO,12690,80116.487937,68747.730,35.999921
48,VALENCIA,48103,89296.188278,72734.910,39.106854
49,VALLADOLID,16044,101641.794166,92628.285,38.150087
50,ZAMORA,3433,83752.301334,74767.500,33.491407
51,ZARAGOZA,23198,110172.519208,99607.890,41.006035

In [6]:
top5_income_provinces = province_summary.sort_values(by='Average_income' , ascending=False).head(5)
top5_income_provinces

           nomprov  Customer_count  Average_income  Median_income Average_age
15           CEUTA             513   200515.885152     128699.580   44.007797
30          MADRID          298841   178362.993637     138024.135   45.205564
7   BALEARS, ILLES            9143   171890.951564     122837.220    39.74877
8        BARCELONA           88754   164584.843157     130877.160   39.865144
32         MELILLA             641   149071.944149     117718.365   45.329173

Q2：**신규 가입 상품 찾기**: 고객별로 전월 대비 새로 보유하게 된 상품(0 → 1)을 찾아서, 월별·상품별 신규 가입 건수를 계산하여 전체 기간 중 신규 가입이 가장 많은 상품 5개 출력 (즉, 상품 컬럼 아이디, 예를 들어 ind_nomina_ult1)
- Pandas의 .agg, .diff 함수 사용하지 말 것

In [7]:
df = data.copy()

# 상품
products = ['ind_ahor_fin_ult1', 'ind_aval_fin_ult1',
       'ind_cco_fin_ult1', 'ind_cder_fin_ult1', 'ind_cno_fin_ult1',
       'ind_ctju_fin_ult1', 'ind_ctma_fin_ult1', 'ind_ctop_fin_ult1',
       'ind_ctpp_fin_ult1', 'ind_deco_fin_ult1', 'ind_deme_fin_ult1',
       'ind_dela_fin_ult1', 'ind_ecue_fin_ult1', 'ind_fond_fin_ult1',
       'ind_hip_fin_ult1', 'ind_plan_fin_ult1', 'ind_pres_fin_ult1',
       'ind_reca_fin_ult1', 'ind_tjcr_fin_ult1', 'ind_valo_fin_ult1',
       'ind_viv_fin_ult1', 'ind_nomina_ult1', 'ind_nom_pens_ult1',
       'ind_recibo_ult1'] 

# 제거할 columns
del_columns = ["ind_empleado", "pais_residencia", "sexo", "age", "fecha_alta", "ind_nuevo", "indresi",
                      "antiguedad", "indrel", "indrel_1mes", "tiprel_1mes", "tiprel_1mes", "indext",
                      "conyuemp", "canal_entrada", "indfall", "tipodom", "cod_prov", "nomprov", "renta", "segmento",
                      "ind_actividad_cliente", "ult_fec_cli_1t"]

df = df.drop(columns=del_columns)

In [8]:
# 데이터 프레임을 "ncopders"와 "fecha_dato"의 내림차순으로 정렬
df = df.sort_values(["ncodpers", "fecha_dato"])

# 달 리스트
months = list(df.groupby(by="fecha_dato", as_index=True).sum().index) 
new_product_list = []
# 이웃한 달끼리 상품의 신규 가입 건수 비교
for i in range(len(months)-1):
    df_prev = df.loc[df.loc[:, "fecha_dato"]==months[i], ["ncodpers"]+products].groupby(by="ncodpers", as_index=True).sum()
    df_next = df.loc[df.loc[:, "fecha_dato"]==months[i+1],["ncodpers"]+products].groupby(by="ncodpers", as_index=True).sum()
   
    new_product_df = df_next.sub(df_prev).fillna(0)
    new_product_list.append(new_product_df)
new_product_df = pd.concat(new_product_list, keys=months[1:], names=["fecha_dato", "ncodpers"])

In [9]:
new_product_df

                     ind_ahor_fin_ult1  ind_aval_fin_ult1  ind_cco_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                   0.0                0.0               0.0
           15890                   0.0                0.0               0.0
           15892                   0.0                0.0               0.0
           15893                   0.0                0.0               0.0
           15894                   0.0                0.0               0.0
...                                ...                ...               ...
2016-05-28 1553685                 0.0                0.0               0.0
           1553686                 0.0                0.0               0.0
           1553687                 0.0                0.0               0.0
           1553688                 0.0                0.0               0.0
           1553689                 0.0                0.0               0.0

                     ind_cder_fin_ult1  ind_cno_fin_ult1  ind_ctju_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                   0.0               0.0                0.0
           15890                   0.0               0.0                0.0
           15892                   0.0               0.0                0.0
           15893                   0.0               0.0                0.0
           15894                   0.0              -1.0                0.0
...                                ...               ...                ...
2016-05-28 1553685                 0.0               0.0                0.0
           1553686                 0.0               0.0                0.0
           1553687                 0.0               0.0                0.0
           1553688                 0.0               0.0                0.0
           1553689                 0.0               0.0                0.0

                     ind_ctma_fin_ult1  ind_ctop_fin_ult1  ind_ctpp_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                   0.0                0.0                0.0
           15890                   0.0                0.0                0.0
           15892                   0.0                0.0                0.0
           15893                   0.0                0.0                0.0
           15894                   0.0                0.0                0.0
...                                ...                ...                ...
2016-05-28 1553685                 0.0                0.0                0.0
           1553686                 0.0                0.0                0.0
           1553687                 0.0                0.0                0.0
           1553688                 0.0                0.0                0.0
           1553689                 0.0                0.0                0.0

                     ind_deco_fin_ult1  ...  ind_hip_fin_ult1  \
fecha_dato ncodpers                     ...
2015-02-28 15889                   0.0  ...               0.0
           15890                   0.0  ...               0.0
           15892                   0.0  ...               0.0
           15893                   0.0  ...               0.0
           15894                   0.0  ...               0.0
...                                ...  ...               ...
2016-05-28 1553685                 0.0  ...               0.0
           1553686                 0.0  ...               0.0
           1553687                 0.0  ...               0.0
           1553688                 0.0  ...               0.0
           1553689                 0.0  ...               0.0

                     ind_plan_fin_ult1  ind_pres_fin_ult1  ind_reca_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                   0.0                0.0                0.0
           15890                   0.0                0.0                0.0
           15892                   0.0                0.0                0.0
           15893                   0.0                0.0                0.0
           15894                   0.0                0.0                0.0
...                                ...                ...                ...
2016-05-28 1553685                 0.0                0.0                0.0
           1553686                 0.0                0.0                0.0
           1553687                 0.0                0.0                0.0
           1553688                 0.0                0.0                0.0
           1553689                 0.0                0.0                0.0

                     ind_tjcr_fin_ult1  ind_valo_fin_ult1  ind_viv_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                  -1.0                0.0               0.0
           15890                   0.0                0.0               0.0
           15892                   0.0                0.0               0.0
           15893                   0.0                0.0               0.0
           15894                   0.0                0.0               0.0
...                                ...                ...               ...
2016-05-28 1553685                 0.0                0.0               0.0
           1553686                 0.0                0.0               0.0
           1553687                 0.0                0.0               0.0
           1553688                 0.0                0.0               0.0
           1553689                 0.0                0.0               0.0

                     ind_nomina_ult1  ind_nom_pens_ult1  ind_recibo_ult1
fecha_dato ncodpers
2015-02-28 15889                 0.0                0.0              0.0
           15890                 0.0                0.0              0.0
           15892                 0.0                0.0              0.0
           15893                 0.0                0.0              0.0
           15894                 0.0                0.0              0.0
...                              ...                ...              ...
2016-05-28 1553685               0.0                0.0              0.0
           1553686               0.0                0.0              0.0
           1553687               0.0                0.0              0.0
           1553688               0.0                0.0              0.0
           1553689               0.0                0.0              0.0

[13055287 rows x 24 columns]

In [10]:
# 지난 달과 달리 다음 달에 신규 가입한 상품만 True라고 표시한 데이터 프레임
total = new_product_df == 1 
total

                     ind_ahor_fin_ult1  ind_aval_fin_ult1  ind_cco_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                 False              False             False
           15890                 False              False             False
           15892                 False              False             False
           15893                 False              False             False
           15894                 False              False             False
...                                ...                ...               ...
2016-05-28 1553685               False              False             False
           1553686               False              False             False
           1553687               False              False             False
           1553688               False              False             False
           1553689               False              False             False

                     ind_cder_fin_ult1  ind_cno_fin_ult1  ind_ctju_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                 False             False              False
           15890                 False             False              False
           15892                 False             False              False
           15893                 False             False              False
           15894                 False             False              False
...                                ...               ...                ...
2016-05-28 1553685               False             False              False
           1553686               False             False              False
           1553687               False             False              False
           1553688               False             False              False
           1553689               False             False              False

                     ind_ctma_fin_ult1  ind_ctop_fin_ult1  ind_ctpp_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                 False              False              False
           15890                 False              False              False
           15892                 False              False              False
           15893                 False              False              False
           15894                 False              False              False
...                                ...                ...                ...
2016-05-28 1553685               False              False              False
           1553686               False              False              False
           1553687               False              False              False
           1553688               False              False              False
           1553689               False              False              False

                     ind_deco_fin_ult1  ...  ind_hip_fin_ult1  \
fecha_dato ncodpers                     ...
2015-02-28 15889                 False  ...             False
           15890                 False  ...             False
           15892                 False  ...             False
           15893                 False  ...             False
           15894                 False  ...             False
...                                ...  ...               ...
2016-05-28 1553685               False  ...             False
           1553686               False  ...             False
           1553687               False  ...             False
           1553688               False  ...             False
           1553689               False  ...             False

                     ind_plan_fin_ult1  ind_pres_fin_ult1  ind_reca_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                 False              False              False
           15890                 False              False              False
           15892                 False              False              False
           15893                 False              False              False
           15894                 False              False              False
...                                ...                ...                ...
2016-05-28 1553685               False              False              False
           1553686               False              False              False
           1553687               False              False              False
           1553688               False              False              False
           1553689               False              False              False

                     ind_tjcr_fin_ult1  ind_valo_fin_ult1  ind_viv_fin_ult1  \
fecha_dato ncodpers
2015-02-28 15889                 False              False             False
           15890                 False              False             False
           15892                 False              False             False
           15893                 False              False             False
           15894                 False              False             False
...                                ...                ...               ...
2016-05-28 1553685               False              False             False
           1553686               False              False             False
           1553687               False              False             False
           1553688               False              False             False
           1553689               False              False             False

                     ind_nomina_ult1  ind_nom_pens_ult1  ind_recibo_ult1
fecha_dato ncodpers
2015-02-28 15889               False              False            False
           15890               False              False            False
           15892               False              False            False
           15893               False              False            False
           15894               False              False            False
...                              ...                ...              ...
2016-05-28 1553685             False              False            False
           1553686             False              False            False
           1553687             False              False            False
           1553688             False              False            False
           1553689             False              False            False

[13055287 rows x 24 columns]

In [11]:
monthly_new = total.groupby(level="fecha_dato").sum()
monthly_new

,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
fecha_dato,,,,,,,,,,,,,,,,,,,,,
2015-02-28,1,1,2132,12,1884,7,291,249,171,348,...,5,27,9,217,3471,259,8,5659,5656,8285
2015-03-28,0,1,2293,15,1786,18,272,284,165,481,...,7,24,12,217,5076,205,4,4479,4473,9135
2015-04-28,0,1,2366,12,1984,10,217,278,167,263,...,4,22,17,871,4627,194,5,2663,5628,8346
2015-05-28,0,0,2264,7,1900,10,205,289,172,238,...,9,21,11,343,4071,201,4,3369,3345,7085
2015-06-28,0,0,6588,9,1857,7,210,213,151,289,...,4,19,8,2931,4655,152,3,5070,8135,9023
2015-07-28,0,0,3056,10,2771,18,191,252,164,265,...,6,27,5,589,4886,232,9,4408,4850,9172
2015-08-28,0,0,5730,10,2412,37,240,231,145,322,...,1,22,13,264,4379,445,2,2950,2968,7115
2015-09-28,0,0,4389,7,1775,22,471,191,122,387,...,8,21,13,271,4463,328,2,4683,4753,11210
2015-10-28,0,0,5682,3,2409,43,468,223,153,349,...,7,19,9,593,4461,911,2,4818,4790,12100
2015-11-28,0,0,4670,6,2930,31,633,209,140,110,...,3,37,8,416,4312,133,5,4395,4409,10102
2015-12-28,0,0,9077,9,3869,69,592,283,155,8,...,3,157,11,235,4295,255,8,5071,5148,9888
2016-01-28,0,1,4436,12,2155,37,545,259,149,0,...,2,104,7,445,3792,739,2,2437,2892,10078
2016-02-28,0,0,3988,9,2211,48,770,217,141,1,...,6,45,6,557,3881,320,2,9499,12687,11528
2016-03-28,0,0,4551,5,2428,45,643,225,131,0,...,2,30,7,199,4401,163,4,4974,5038,10117
2016-04-28,0,0,4027,5,2381,40,596,240,161,0,...,5,21,4,807,4100,128,3,3790,4424,9799
2016-05-28,1,0,3854,5,2346,40,512,226,131,0,...,3,22,7,279,4248,183,7,5488,5513,10163

In [12]:
total = monthly_new.sum()

In [13]:
# 가장 많은 신규 가입상품 건수 5개 출력 과정
tmp = {}
for i in products:
    tmp[i] = total[i]

result = sorted(tmp.items(), key=lambda x : x[1], reverse=True)

prod_name = []
for j in result:
    prod_name.append(j[0])

print(prod_name[:5])

['ind_recibo_ult1', 'ind_nom_pens_ult1', 'ind_nomina_ult1', 'ind_tjcr_fin_ult1', 'ind_cco_fin_ult1']

Q3：**마지막 달** 데이터에서 가입 상품의 개수를 세어 3개 이상 혹은 3개 미만의 여부를 예측하고자 합니다. 다음의 기준 중에서 가입상품 3개 이상 여부에 대해 가장 관련성이 큰 기준을 **chi-square**를 이용해 찾으세요.
- 1) 성별 (H / V)
- 2) 나이 65이상 (senior), 65 미만 30 이상 (adult), 30 미만 (young)
- 3) segment
- 4) ind_empleado (A: 재직, B: 전직 직원, F: 계열사 소속, N: 직원 아님, P: 휴직·소극 상태)
- 5) tiprel_1mes (A: 활동, I: 비활동, P: 전 고객, R: 잠재 고객)

In [14]:
df=data.copy()
print(df.head())

   fecha_dato  ncodpers ind_empleado pais_residencia sexo  age  fecha_alta  \
0  2015-01-28   1375586            N              ES    H   35  2015-01-12
1  2015-01-28   1050611            N              ES    V   23  2012-08-10
2  2015-01-28   1050612            N              ES    V   23  2012-08-10
3  2015-01-28   1050613            N              ES    H   22  2012-08-10
4  2015-01-28   1050614            N              ES    V   23  2012-08-10

   ind_nuevo antiguedad  indrel  ... ind_hip_fin_ult1 ind_plan_fin_ult1  \
0        0.0          6     1.0  ...                0                 0
1        0.0         35     1.0  ...                0                 0
2        0.0         35     1.0  ...                0                 0
3        0.0         35     1.0  ...                0                 0
4        0.0         35     1.0  ...                0                 0

  ind_pres_fin_ult1 ind_reca_fin_ult1 ind_tjcr_fin_ult1 ind_valo_fin_ult1  \
0                 0                 0                 0                 0
1                 0                 0                 0                 0
2                 0                 0                 0                 0
3                 0                 0                 0                 0
4                 0                 0                 0                 0

  ind_viv_fin_ult1 ind_nomina_ult1  ind_nom_pens_ult1  ind_recibo_ult1
0                0             0.0                0.0                0
1                0             0.0                0.0                0
2                0             0.0                0.0                0
3                0             0.0                0.0                0
4                0             0.0                0.0                0

[5 rows x 48 columns]

In [15]:
last_month = df.loc[df['fecha_dato'] == '2016-05-28']

product_cols = [
    'ind_ahor_fin_ult1',
    'ind_aval_fin_ult1',
    'ind_cco_fin_ult1',
    'ind_cder_fin_ult1',
    'ind_cno_fin_ult1',
    'ind_ctju_fin_ult1',
    'ind_ctma_fin_ult1',
    'ind_ctop_fin_ult1',
    'ind_ctpp_fin_ult1',
    'ind_deco_fin_ult1',
    'ind_deme_fin_ult1',
    'ind_dela_fin_ult1',
    'ind_ecue_fin_ult1',
    'ind_fond_fin_ult1',
    'ind_hip_fin_ult1',
    'ind_plan_fin_ult1',
    'ind_pres_fin_ult1',
    'ind_reca_fin_ult1',
    'ind_tjcr_fin_ult1',
    'ind_valo_fin_ult1',
    'ind_viv_fin_ult1',
    'ind_nomina_ult1',
    'ind_nom_pens_ult1',
    'ind_recibo_ult1'
]

# 고객별 가입 상품 개수 계산
last_month['product_count'] = last_month[product_cols].fillna(0).sum(axis=1)

# 상품 3개 이상 / 3개 미만 분류
last_month['product_group'] = np.where(
    last_month['product_count'] >= 3,
    '3plus',
    'less3'
)

# 나이 숫자로 변환
last_month['age'] = pd.to_numeric(last_month['age'], errors='coerce')

last_month['age_group'] = 'unknown'

last_month.loc[last_month['age'] >= 65, 'age_group'] = 'senior'
last_month.loc[
    (last_month['age'] >= 30) & (last_month['age'] < 65),
    'age_group'
] = 'adult'
last_month.loc[last_month['age'] < 30, 'age_group'] = 'young'

In [16]:
# 카이제곱 검정 대상 변수
features = [
    'sexo',
    'age_group',
    'segmento',
    'ind_empleado',
    'tiprel_1mes'
]

results = []

for feature in features:

    # 필요한 데이터 선택 후 결측값 제거
    sub_data = last_month[[feature, 'product_group']].dropna()

    if feature == 'age_group':
        sub_data = sub_data.loc[sub_data['age_group'] != 'unknown']

    # 교차표 만들기
    table = pd.crosstab(
        sub_data[feature],
        sub_data['product_group']
    )

    # 카이제곱 검정
    chi2, p_value, dof, expected = chi2_contingency(table)

    results.append({
        'feature': feature,
        'chi2': chi2,
        'p_value': p_value
    })


result = pd.DataFrame(results)
result = result.sort_values('chi2', ascending=False)

print('카이제곱 검정 결과')
print(result)

print('가장 관련성이 큰 기준:', result.iloc[0]['feature'])

카이제곱 검정 결과
        feature           chi2        p_value
4   tiprel_1mes  183808.591523   0.000000e+00
2      segmento  124374.548799   0.000000e+00
1     age_group   61002.202414   0.000000e+00
0          sexo    3412.231367   0.000000e+00
3  ind_empleado    1343.689088  1.120822e-289
가장 관련성이 큰 기준: tiprel_1mes